@echo off
echo Freeing port 8080 if occupied...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8080') do taskkill /f /pid %%a >nul 2>&1
echo Starting CodeArena Spring Boot Backend Server...
..\maven\bin\mvn.cmd spring-boot:run
